# Generated by Django 3.2 on 2022-04-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['event_date_and_time']},
        ),
        migrations.AddField(
            model_name='registration',
            name='guest',
            field=models.BooleanField(default=False),
        ),
    ]
